---
- name: Deploy Hello Service
  hosts: app_servers
  become: yes
  vars:
    production_domain: "abu-production.chickenkiller.com"
    staging_domain:    "abu-staging.chickenkiller.com"
    enable_ssl: true
    cert_email: "aliyuatikuabubakar7@gmail.com"

  roles:
    - common
    - app
    - nginx
    - certbot
