version: '3.8'

services:
  hello-svc:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: hello-svc
    environment:
      - ENV=${ENV}
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
